# Generated by Django 4.1.4 on 2022-12-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User Email')),
                ('telephone', models.CharField(max_length=30)),
                ('choix', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(verbose_name='Last Updated')),
            ],
        ),
    ]
