# Generated by Django 4.1.4 on 2023-02-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteUser',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=30, unique=True)),
                ('last_name', models.CharField(max_length=30, unique=True)),
                ('telephone', models.CharField(max_length=30, unique=True)),
                ('choix', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=250)),
            ],
        ),
    ]
