# Generated by Django 4.1.4 on 2023-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voteuser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
