# Generated by Django 4.1.4 on 2023-01-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_voteuser_id_alter_voteuser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voteuser',
            name='email',
        ),
        migrations.AlterField(
            model_name='voteuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
