# Generated by Django 4.1.4 on 2023-02-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_rename_user_id_voteuser_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User_rcsm',
        ),
    ]
