# Generated by Django 4.1.4 on 2023-02-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_users_user_rcsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteuser',
            name='adresse',
            field=models.CharField(default=False, max_length=250),
        ),
        migrations.AddField(
            model_name='voteuser',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voteuser',
            name='ville',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
