# Generated by Django 4.1.4 on 2023-02-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_voteuser_adresse_voteuser_status_voteuser_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voteuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='voteuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
